### ISSUE TITLE
Handle private routes when logged out

### ISSUE THREAD

**Issue by abheist** [abheist/goldenSwan-frontend#1]
👎**Current behaviour:** When a user is not logged in and try to get to the private route, no screen is showing.

👍**Expected behaviour:** User should see the login page with the **ref** to the private route. Also if that route is not present even in private routes, then the page should be 404.

## Todo
- [ ] When a user tries to access private route, the user should redirect to the login page with **ref** of the current page which user was trying to access.
- [ ] Login screen with the private route with **ref** in URL should redirect the user to **ref** page after login.
- [ ] If the route doesn't exist in private route, then the user should see a 404 page.
